name: Playwright Tests
on:
  push:
    branches:
      - 'master'
jobs:
  redmine-tests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: run test
        run: npm run test 
      - name: Copy History
        if: always()
        run: cp -r ./docs/history/ ./allure-results/history/
      - name: Allure fix
        run: rm -rf .git/hooks
      - name: Install
        run: npm install
      - name: Generate Report
        if: always()
        run: npx allure generate allure-results -o allure-report --clean
      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-results
          path: ./allure-results                  
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: allure-report        
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          branch: master 
          folder: allure-report
          target-folder: docs
      - name: Pushes docs to another repository
        uses: cpina/github-action-push-to-another-repository@v1.3
        if: always()
        env:
          API_TOKEN_GITHUB: ${{ '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' }}
        with:
          source-directory: 'docs'
          destination-github-username: 'SRVFLLN'
          destination-repository-name: 'Allure-reports'
          user-email: servefallen@gmail.com 
          target-branch: main 
